// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("MessageRouter.Interfaces")]
[assembly: AssemblyProductAttribute("MessageRouter")]
[assembly: AssemblyDescriptionAttribute("A CQRS (event driven) message router in F#")]
[assembly: AssemblyVersionAttribute("1.4.0")]
[assembly: AssemblyFileVersionAttribute("1.4.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.4.0";
    }
}
