// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("MessageRouter.Common")]
[assembly: AssemblyProductAttribute("MessageRouter")]
[assembly: AssemblyDescriptionAttribute("MessageRouter")]
[assembly: AssemblyVersionAttribute("2.0.1")]
[assembly: AssemblyFileVersionAttribute("2.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.1";
    }
}
